### ISSUE TITLE
Time to train?

### ISSUE THREAD

**Issue by stephanedebove** [mohamedkeid/Feed-Forward-Style-Transfer#3]
Hi,

thanks for you work and for sharing, any idea how long it would take to train on a "common PC", RAM 16GB and 2GB 3 years old GPU?

Also are there any restrictions on the size (resolution) of the input and output images?

**Comment by mkeid** [comment]
Hey Stéphane,

Training time will vary considerably based on input size and parameter
values. The restrictions on input and out sizes will depend on GPU memory.
I used rather small dimensions for my examples because they were simply
faster to train. It ultimately depends what you're trying to use the model
for.

**Comment by stephanedebove** [comment]
Thanks for the reply. Can you give examples of your own parameters and running times? I just want to know if it's more something like a couple of minutes, a couple of hours or a couple of days, I don't need an exact time.

**Comment by mkeid** [comment]
With a Titan X Pascal, 64 gigs of RAM, and 3.5ish GHz i7 it took me a few
hours I believe. The parameters vary based on the artwork.
